Update WiFi to use *only* ANT1.
This is ANT1 (J3), "Path A" for 2GHz and 5GHz which on the JODY
module is the connector that sits alone on one side of the board
cutout screw.

This reduces price at the cost of a reduction in max speed.

diff --git a/scripts/package-build/linux-kernel/build_iGOS_drivers/build_iGOS_drivers b/scripts/package-build/linux-kernel/build_iGOS_drivers/build_iGOS_drivers
--- a/scripts/package-build/linux-kernel/build_iGOS_drivers/build_iGOS_drivers
+++ b/scripts/package-build/linux-kernel/build_iGOS_drivers/build_iGOS_drivers
@@ -27,6 +27,13 @@ do
         if [ -f $PATCH ]; then
             echo "=== Applying patch $PATCH to $(realpath $i)"
             patch -d $i -p1 < $PATCH
+        elif [ "$i" = 'imx-firmware' ]; then
+            # No patch seems REALLY unlikely since we always need PSL custom
+            # wifi_mod_para.conf
+            echo "=== fatal: cannot find patch $PATCH which seems unlikely."
+            echo "=== If you have updated the branch number you will need to"
+            echo "=== regenerate a suitable patch"
+            exit 1
         fi
     fi
 done
